### ISSUE TITLE
why have you been passing Context through the services and repos ?

### ISSUE THREAD

**Issue by aliuygur** [CaptainCodeman/clean-go#2]
hello dear, 

I have to say that this is great repository. But I am confused about the subject ?

why have you been passing Context through the services and repos ?

**Comment by CaptainCodeman** [comment]
Context is required to call some remote services (e.g. AppEngine datastore) but even when it isn't, it could be useful for cancelling things, timeouts etc...

**Comment by alioygur** [comment]
I think so. Thank you so much.
